apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parasol-web
  description: "Parasol Web Application for the Red Hat PE Workshop"
  owner: redhat-pe-workshop
  annotations:
    argocd/app-selector: rhdh.app/name=parasol
    argocd/instance-name: appsargocd
    github.com/project-slug: rhdh-demo-gh/parasol-web
    backstage.io/techdocs-ref: url:https://github.com/redhat-pe-workshop/parasol-web
    quay.io/repository-slug: rhdh-demo/parasol-web
  tags:
    - web
    - application
    - redhat
    - parasol
  links:
    - url: https://parasol-web-parasol.apps.cluster-sfkb4.sfkb4.sandbox3121.opentlc.com/
      title: Production Site
      icon: web
spec:
  type: service
  lifecycle: experimental
  owner: group:rhdh-demo-gh/docs-team
  system: parasol
  repository: https://github.com/redhat-pe-workshop/parasol-web
  dependsOn:
    - component:default/parasol-store-app
  consumesApis:
    - default/parasol-store-app-api
